version: "3.9"
services:
  app:
    container_name: "cmr-app"
    build: ./infra/php
    volumes:
      - ./src:/data

  web:
    container_name: "cmr-nginx"
    image: nginx:1.25-alpine
    ports:
      - 8081:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    container_name: "cmr-mysql"
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: